### PR TITLE
BINLOG_ADAPT_CONCEPT: namespace support

### LINKED ISSUE #154: BINLOG_ADAPT_CONCEPT does not support namespaces
```cpp
namespace  ns {

template<typename T>
concept Concept2 = requires(T t)
{
    {t.A} -> std::convertible_to<std::string_view>;
    {t.B} -> std::convertible_to<std::string_view>;
};

} // namespace  ns

BINLOG_ADAPT_CONCEPT(ns::Concept2, A, B)
```

```
../../source/utils/test/test_serialize.cpp:33:22: error: template argument for template type parameter must be a type; did you forget 'typename'?
BINLOG_ADAPT_CONCEPT(ns::Concept2, A, B)
                     ^
                     typename
_deps/binlog-src/include/binlog/adapt_struct.hpp:153:79: note: expanded from macro 'BINLOG_ADAPT_CONCEPT'
  MSERIALIZE_EXPAND(MSERIALIZE_MAKE_TEMPLATE_SERIALIZABLE((Concept Concept), (Concept) __VA_OPT__(,) __VA_ARGS__)) \
                                                                              ^
_deps/binlog-src/include/mserialize/make_template_serializable.hpp:63:59: note: expanded from macro 'MSERIALIZE_MAKE_TEMPLATE_SERIALIZABLE'
    :StructSerializer<MSERIALIZE_UNTUPLE(MSERIALIZE_FIRST(__VA_ARGS__)) \
                                                          ^
_deps/binlog-src/include/mserialize/detail/preprocessor.hpp:8:68: note: expanded from macro 'MSERIALIZE_FIRST'
#define MSERIALIZE_FIRST(...) MSERIALIZE_EXPAND(MSERIALIZE_FIRST_I(__VA_ARGS__, 0))
                                                                   ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
_deps/binlog-src/include/mserialize/detail/preprocessor.hpp:20:52: note: expanded from macro 'MSERIALIZE_UNTUPLE'
#define MSERIALIZE_UNTUPLE(a) MSERIALIZE_UNTUPLE_I a
                                                   ^
_deps/binlog-src/include/mserialize/detail/preprocessor.hpp:21:35: note: expanded from macro 'MSERIALIZE_UNTUPLE_I'
#define MSERIALIZE_UNTUPLE_I(...) __VA_ARGS__
                                  ^
_deps/binlog-src/include/mserialize/detail/preprocessor.hpp:5:30: note: expanded from macro 'MSERIALIZE_EXPAND'
#define MSERIALIZE_EXPAND(x) x
                             ^
_deps/binlog-src/include/mserialize/StructSerializer.hpp:88:20: note: template parameter is declared here
template <typename T, typename... Members>
```

### PR DESCRIPTION
**Pull request by erenon**
Fixes #154

### CODE REVIEW

File: test/integration/LoggingAdaptedConcepts.cpp [hunk 1]
```diff
@@ -81,6 +99,9 @@ int main()
   BINLOG_INFO("{}", Wrap<int>{456});
   // Outputs: Wrap{ a: 456 }
 
+  BINLOG_INFO("{}", NsFoo{});
+  // Outputs: Stringable{ ns_str: bar }
```
Comment (andrewkcorcoran) [inline test/integration/LoggingAdaptedConcepts.cpp:103]: Should it be outputting `ns::Stringable...`?

**Review by andrewkcorcoran — COMMENTED** [review]
Any unit tests for concepts with a namespace to ensure that the namespace is also output?

File: include/binlog/adapt_struct.hpp [hunk 2]
```diff
@@ -154,6 +154,32 @@
...
+ *     {
+ *       { a.str() } -> std::convertible_to<std::string>;
+ *     };
+ *     }
+ *
+ *     BINLOG_ADAPT_CONCEPT_NS(ns, Stringable, str)
+ *
+ * @see BINLOG_ADAPT_CONCEPT
+ */
+#define BINLOG_ADAPT_CONCEPT_NS(Ns, Concept, ...)                                                                      \
```
Comment (andrewkcorcoran) [inline include/binlog/adapt_struct.hpp:177]: I would argue that the majority of time concepts will be in namespaces so perhaps the default macro should support that rather than it being the exception? Is it possible for the macro to support passing in the fully qualified type name (including the namespace) similar to how `ADAPT_STRUCT` works or is that not technically feasible?

Comment (erenon) [reply include/binlog/adapt_struct.hpp]: Thanks for your persistence and reminding me how the other parts work already! I changed `BINLOG_ADAPT_CONCEPT` to work with namespaced concepts naturally.

File: test/integration/LoggingAdaptedConcepts.cpp (hunk 1 above)
Comment (erenon) [reply test/integration/LoggingAdaptedConcepts.cpp]: Fixed

**Comment by erenon** [comment]
@andrewkcorcoran Can you give an example type + concept + adaption that reproduces the issue? I wasn't able to repro.

**Comment by andrewkcorcoran** [comment]
In creating the below I was able to figure out that the issue looks to be related to inheritance, perhaps because `Derived` and `Base` both satisfy `Concept` binlog is having issues?

```cpp
#include <concepts>
#include <cstdlib>

#include "binlog/binlog.hpp"

namespace ns {

template<typename T>
concept Concept = requires(const T const_t)
{
    { const_t.Method() } -> std::convertible_to<std::string_view>;
};

struct Base
{
    std::string_view Method() const { return "text"; }
};
static_assert(Concept<Base>);

struct Derived : public Base
{};
static_assert(Concept<Base>);

} // namespace ns

BINLOG_ADAPT_CONCEPT(ns::Concept, Method)

template<ns::Concept T>
void Log(const T & t)
{
    BINLOG_INFO("{}", t);
}

int main()
{
    Log(ns::Derived{});
    return EXIT_SUCCESS;
}
```

**Comment by erenon** [comment]
@andrewkcorcoran The "derived" issue should be fixed now, see the most recent commit. Please see if your test suite passes.

**Review by andrewkcorcoran — APPROVED** [review]

**Comment by erenon** [comment]
@spektrof please merge this, thanks!

**Review by spektrof — APPROVED** [review]
